/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const AnimesIndexLazyImport = createFileRoute('/animes/')()
const AnimesIdLazyImport = createFileRoute('/animes/$id')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const AnimesIndexLazyRoute = AnimesIndexLazyImport.update({
  path: '/animes/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/animes/index.lazy').then((d) => d.Route))

const AnimesIdLazyRoute = AnimesIdLazyImport.update({
  path: '/animes/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/animes/$id.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/animes/$id': {
      id: '/animes/$id'
      path: '/animes/$id'
      fullPath: '/animes/$id'
      preLoaderRoute: typeof AnimesIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/animes/': {
      id: '/animes/'
      path: '/animes'
      fullPath: '/animes'
      preLoaderRoute: typeof AnimesIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/animes/$id': typeof AnimesIdLazyRoute
  '/animes': typeof AnimesIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/animes/$id': typeof AnimesIdLazyRoute
  '/animes': typeof AnimesIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/animes/$id': typeof AnimesIdLazyRoute
  '/animes/': typeof AnimesIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/animes/$id' | '/animes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/animes/$id' | '/animes'
  id: '__root__' | '/' | '/animes/$id' | '/animes/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AnimesIdLazyRoute: typeof AnimesIdLazyRoute
  AnimesIndexLazyRoute: typeof AnimesIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AnimesIdLazyRoute: AnimesIdLazyRoute,
  AnimesIndexLazyRoute: AnimesIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/animes/$id",
        "/animes/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/animes/$id": {
      "filePath": "animes/$id.lazy.tsx"
    },
    "/animes/": {
      "filePath": "animes/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
